### ISSUE TITLE
Text Under Post - Submit Post via Utopian

### ISSUE THREAD

**Issue by arietm** [utopian-io/utopian.io#68] opened 2017-11-09 20:18 UTC
When I make a post about the previous bug about steemit market, I realize there is another bug that occurs when I want to make a post via utopian. so i made a video record and also made a gif image, what happened

This bug happens at the bottom of our post. I did not write /n/n in post edit feature. but when I always create and click submit post. suddenly /n/n appears below my post.

# /n/n under post 

#### Before submit post

![2017-11-10 at 02-50-42.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510257697/gmkesvns9xdiofw8gcvc.png)

### After submit post

![2017-11-10 at 02-54-30.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510257750/xpmv7pj03z5h6sfmr9zb.png)

### GIF image 

<center>
![ezgif.com-video-to-gif (6).gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510257809/y2wabhcvozhyylgl8tpo.gif)
</center>

<center>
Author : @arie.steem
Adsactly & Utopian-io
</center>

Communite With Us In
Discord ADSactly :https://discordapp.com/invite/6jAXNuu
Discord utopian.io :https://discord.gg/72bPmxk/n/n<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@arie.steem/text-under-post-submit-post-via-utopian">Utopian.io</a></em><hr/>

**Comment by azarus** [comment] 2018-02-13 23:35
@wehmoen this issue had probably been solved already as i am unable to reproduce it. Please close it.

**Closed** 2018-02-14 00:26 UTC
