### ISSUE TITLE
Dropdown menu is not scrolling properly

### ISSUE THREAD

**Issue by WhiteRaidho** [utopian-io/utopian.io#143] opened 2017-11-23 13:23 UTC
## Issue
Dropdown menu in right corner is fixed to page, not to screen. During scrolling page with open this menu it move with page content.

Screenshots:

![bug1.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511379223/mfp2dhr5xha7fcsfrvey.png)

![bug2.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511379234/bxrpxbpoomj6eznp9y9z.png)

![Przechwytywanie.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511379246/gfsp7xlj6g7vovvcc6i5.png)

It's similar situation to [this](https://utopian.io/utopian-io/@raidho/search-combobox-is-not-scroll-properly).
I am using Google Chrome v62.0.3209.94 (64-bit) on Windows 10.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@raidho/dropdown-menu-is-not-scrolling-properly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by sirrius-a-b** [comment] 2017-12-10 19:14
Thiss seems to be a duplicate of #95. And was already fixed and merged here: #100.

**Closed** 2017-12-18 14:21 UTC
