### ISSUE TITLE
Issue: Duplicating text when Editing Posts

### ISSUE THREAD

**Issue by deveerei** [utopian-io/utopian.io#36] opened 2017-11-02 17:16 UTC
Hi,

I've encountered this countless times. When Editing a Post in Utopian and adding some text there, e.g a line or two of text. It gets duplicated when Submitting the post again. However in the preview it isn't.

Edit Post > Add Something 1 line > View post > Has 2x that line 

Sometimes the duplicate part appears right after the original or on someplace else.

Check this out for sample: https://steemitstage.com/utopian-io/@deveerei/recreating-voxel-js-logo-with-material-design-principles

The line that says "You can get the .PSD file from my 4Shared files." was repeated.

It also happens on Images.

* Browser: Google Chrome Canary
* Operating system: Windows 10

Another issue - chrome closes when uploading images using utopian (as well as nd.busy.org)

**Comment by azarus** [comment] 2018-02-13 22:06
@deveerei Thank you for opening the issue, however i am unable to reproduce this. Please let us know if this issue apears again. Also next time please give more detailed steps how to reproduce this. Thank you.

@wehmoen issue can be closed as its either been fixed or can't be reproduced.

**Closed** 2018-02-13 22:15 UTC
